//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rowan.TfsWorkingOn.WinForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rowan.TfsWorkingOn.WinForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string ConnectionFailedTitle {
            get {
                return ResourceManager.GetString("ConnectionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the work item you are working on....
        /// </summary>
        internal static string DoubleClickToSelect {
            get {
                return ResourceManager.GetString("DoubleClickToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect: {0}.
        /// </summary>
        internal static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields are invalid:.
        /// </summary>
        internal static string FollowingFieldsInvalid {
            get {
                return ResourceManager.GetString("FollowingFieldsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Monitor User Activity causes an automatic 
        ///Stop/Pause &quot;working on&quot; when the computer has 
        ///been idle for the time out specified (minutes). When
        ///user activity begins again, the Start/Resume &quot;working
        ///on&quot; is triggered..
        /// </summary>
        internal static string HelpActivityMonitor {
            get {
                return ResourceManager.GetString("HelpActivityMonitor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap helpImage {
            get {
                object obj = ResourceManager.GetObject("helpImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Query selected will be displayed in the system tray 
        ///context menu, with the work items from the query results 
        ///shown in a sub menu. This allows fast work item switching
        ///as a work item can be selected to start working on without 
        ///going to the find work item search dialog..
        /// </summary>
        internal static string HelpMenuQuery {
            get {
                return ResourceManager.GetString("HelpMenuQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Nag causes a balloon notification 
        ///to be displayed at the set interval (minutes)
        ///if no work item is being worked on. .
        /// </summary>
        internal static string HelpNag {
            get {
                return ResourceManager.GetString("HelpNag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a time out occurs, on resuming, you are prompted 
        ///if you were working on the work item away from your 
        ///computer. If so, the inactive time is added to your working 
        ///on time, otherwise it is removed..
        /// </summary>
        internal static string HelpPromptOnResume {
            get {
                return ResourceManager.GetString("HelpPromptOnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fields.
        /// </summary>
        internal static string InvalidFields {
            get {
                return ResourceManager.GetString("InvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item already updated.
        /// </summary>
        internal static string ItemAlreadyUpdated {
            get {
                return ResourceManager.GetString("ItemAlreadyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before configuring the work item type field mappings, please set the Mapping Path..
        /// </summary>
        internal static string MappingPath {
            get {
                return ResourceManager.GetString("MappingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Mapping Path.
        /// </summary>
        internal static string MappingPathTitle {
            get {
                return ResourceManager.GetString("MappingPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select what you are working on!.
        /// </summary>
        internal static string NagMessage {
            get {
                return ResourceManager.GetString("NagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Working On....
        /// </summary>
        internal static string NotifyIconText {
            get {
                return ResourceManager.GetString("NotifyIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are outstanding changes. Would you like to save your changes?.
        /// </summary>
        internal static string OutstandingChanges {
            get {
                return ResourceManager.GetString("OutstandingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused Working On {0}: {1}.
        /// </summary>
        internal static string PausedWorkingOn {
            get {
                return ResourceManager.GetString("PausedWorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume working on....
        /// </summary>
        internal static string PromptOnResumeCaption {
            get {
                return ResourceManager.GetString("PromptOnResumeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were you working on &quot;{0}: {1}&quot; while you were away from your computer?
        ///
        ///Yes to record the time away and continue
        ///No to not record the time away and resume
        ///Cancel to not record the time away and not resume.
        /// </summary>
        internal static string PromptOnResumeText {
            get {
                return ResourceManager.GetString("PromptOnResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to discard your changes and refresh the work item?.
        /// </summary>
        internal static string RefreshWorkItem {
            get {
                return ResourceManager.GetString("RefreshWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed.
        /// </summary>
        internal static string Resumed {
            get {
                return ResourceManager.GetString("Resumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed Working On {0}: {1}.
        /// </summary>
        internal static string ResumedWorkingOn {
            get {
                return ResourceManager.GetString("ResumedWorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Work Items in {0}.
        /// </summary>
        internal static string SearchForWorkItemsIn {
            get {
                return ResourceManager.GetString("SearchForWorkItemsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started working on {0}: 
        ///{1}.
        /// </summary>
        internal static string StartedWorkingOn {
            get {
                return ResourceManager.GetString("StartedWorkingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop current Work Item.
        /// </summary>
        internal static string StopCurrentWorkItem {
            get {
                return ResourceManager.GetString("StopCurrentWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped working on {0}: 
        ///{1}.
        /// </summary>
        internal static string StoppedWorkingOn {
            get {
                return ResourceManager.GetString("StoppedWorkingOn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Stopwatch_Blue {
            get {
                object obj = ResourceManager.GetObject("Stopwatch_Blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Stopwatch_Green {
            get {
                object obj = ResourceManager.GetObject("Stopwatch_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Stopwatch_Red {
            get {
                object obj = ResourceManager.GetObject("Stopwatch_Red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to stop working on Work Item: {0}?.
        /// </summary>
        internal static string StopWorkingOnWorkItem {
            get {
                return ResourceManager.GetString("StopWorkingOnWorkItem", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tfsworkingon {
            get {
                object obj = ResourceManager.GetObject("tfsworkingon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item {0}: {1}.
        /// </summary>
        internal static string WorkItemTitle {
            get {
                return ResourceManager.GetString("WorkItemTitle", resourceCulture);
            }
        }
    }
}
